global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 10.0
    height: 10.0
    origin_x: -5.0
    origin_y: -5.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]