local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 3.0
    height: 3.0
    resolution: 0.05
    rolling_window: true
    plugins: ["obstacle_layer", "inflation_layer"]