ekf_node:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    base_link_frame: base_link

    two_d_mode: true

    frequency: 50.0

    odom0: husky_velocity_controller/odom
    #odom0: odom
    odom0_config: [true, true, false,  # x, y, z
                   false, false, false,
                   true, true, false,  # vx, vy, vz
                   false, false, false,
                   false, false, false]

    odom0_differential: false
    odom0_queue_size: 10

    imu0: imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  false, false, false]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
