slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: "mapping"
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    use_scan_matching: true
    map_start_pose: [0.0, 0.0, 0.0]
    publish_tf_map: true
    publish_pose_to_tf: true

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan

    transform_publish_period: 0.05
    map_update_interval: 2.0
    publish_period: 1.0
    use_scan_barycenter: true
    num_particles: 80
    minimum_score: 200

    # Opcionales recomendados
    use_splitting_validation: true
    use_least_square: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174
